version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_container
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: wp_database
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: 1234
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wp_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
