name: Mushroomsoft CI Tests

on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: GitHub Actions - Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          always-auth: true
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm i
        
      - name: Lint code
        run: npm run lint

      - name: Run UI tests
        run: npm run test

      - name: Build
        run: npm run build 

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN_KEY }}
          branch: MUAN-test
          folder: dist/mushroomsoft-ws