name: CI with OpenID Connect

on:
  push:
    branches: [master]

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  build:
    name: GitHub Actions - Deploy to Azure Blob Storage - Development
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
    env:
      COPILOT_URL_TOKEN: ${{ secrets.COPILOT_URL_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Crear archivo .env
        run: |
          echo "COPILOT_URL_TOKEN=$COPILOT_URL_TOKEN" > .env

      - name: Build project
        run: npm run build

      - name: Eliminar archivo .env
        run: rm .env

      - name: Create and Publish versions
        id: changesets
        uses: changesets/action@v1.4.1
        with:
          version: npm run version-packages
          commit: "chore: update versions"
          title: "chore: update versions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Extract version for tagging and naming artifacts
      - name: Extract Version
        id: extract-version
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

    outputs:
      version: ${{ steps.extract-version.outputs.VERSION }}

  publish-artifacts:
    needs: build
    if: needs.build.outputs.version != ''
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          COPILOT_URL_TOKEN: ${{ secrets.COPILOT_URL_TOKEN }}

      - name: Create Deployment Package
        run: |
          cd dist/browser
          zip -r ../../mushroomsoft-app-${{ needs.build.outputs.version }}.zip ./*
          cd ../..

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mushroomsoft-app-${{ needs.build.outputs.version }}
          path: mushroomsoft-app-${{ needs.build.outputs.version }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.build.outputs.version }}
          name: Release v${{ needs.build.outputs.version }}
          files: mushroomsoft-app-${{ needs.build.outputs.version }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      version: ${{ needs.build.outputs.version }}

  deploy-specific-version:
    name: Deploy Specific Version
    needs: publish-artifacts
    if: needs.publish-artifacts.outputs.version != ''
    uses: ./.github/workflows/deploy-app-azure.yml
    with:
      version: ${{ needs.publish-artifacts.outputs.version }}
    secrets: inherit
