name: Mushroomsoft Employees Data Fetch Process

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [20]

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MUSHROOMSOFT_TOKEN }}

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Running Script
        run: node ./scripts/mushroomsoftEmployeesData.js
        env:
          POWER_AUTOMATE_URL: ${{secrets.POWER_AUTOMATE_URL}}

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated Change by Power Automate
