name: Mushroomsoft Employees Data Fetch Process

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [20]

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Running Script
        run: node ./scripts/mushroomsoftEmployeesData.js

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automated Change by Power Automate
          commit_author: Power Platform
