name: Manual Deploy App to Azure
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the app to deploy"
        required: true
        type: string
jobs:
  call-deploy-app-azure:
    uses: ./.github/workflows/deploy-app-azure.yml
    with:
      version: ${{ github.event.inputs.version }}
    secrets: inherit
