name: MushroomSoft Release and Deploy Production
description: |
  This workflow builds the project and deploys it to GitHub Pages.
  It is triggered on push to the main branch and can also be manually triggered.

on:
  workflow_dispatch:

jobs:
  build:
    name: GitHub Actions - Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          always-auth: true
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          PRO_COPILOT_URL_TOKEN: ${{ secrets.COPILOT_URL_TOKEN }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN_KEY }}
          branch: gh-pages
          folder: dist/browser
